### PR TITLE
Make PointCloudLibraryPlugin filters-library compatible with VTK > 5

### PR DESCRIPTION
**Pull request by fbudin69500**

### CODE REVIEW

**Comment by patmarion** [comment]
Thanks!  Does this compile with `director/master`?  Does the `CMakeLists.txt` need to be updated too?  Last month I made the necessary local changes to build this with vtk7.1 but I'm not at that computer so I don't remember what's in my diff.  Sorry I didn't get around to committing it!

**Comment by fbudin69500** [comment]
Yes, it builds on my computer for `director/master` with `USE_PRECOMPILED_VTK` set to `ON` . The `CMakeLists.txt` does not need to be updated.

**Comment by patmarion** [comment]
hmm, i would have thought this line would need to be updated:

https://github.com/patmarion/PointCloudLibraryPlugin/blob/filters-library/Filters/CMakeLists.txt#L41

**Comment by patmarion** [comment]
Anyway, I merged it now since this is a good change and I will test the build to verify it's working.  Thanks!

**Pull request merged**
